package models

type Supplier struct {
	ParterID                      string
	PartnerName                   string
	CustomerID                    string
	CustomerName                  string
	CustomerDomainName            string
	CustomerCountry               string
	MpnID                         int
	Tier2MpnID                    int
	InvoiceNumber                 string
	ProductID                     string
	SKUID                         string
	AvailabilityID                string
	SKUName                       string
	ProductName                   string
	PublisherName                 string
	PublisherID                   string
	SubscriptionDescription       string
	SubscriptionID                string
	ChargeStartDate               string
	ChargeEndDate                 string
	UsageDate                     string
	MeterType                     string
	MeterCategory                 string
	MeterID                       string
	MeterSubCategory              string
	MeterName                     string
	MeterRegion                   string
	Unit                          string
	ResourceLocation              string
	CostomerService               string
	ResourceGroup                 string
	ResourceURI                   string
	ChargeType                    string
	UnitPrice                     float64
	Quantity                      float64
	UnitType                      string
	BillingPreTaxTotal            float64
	BillingCurrency               string
	PricingPreTaxTotal            float64
	PricingCurrency               string
	ServiceInfo1                  string
	ServiceInfo2                  string
	Tags                          string
	AdditionalInfo                string
	EffectiveUnitPrice            float64
	PCToBCExchangeRate            int
	PCToBCExchangeRateDate        string
	EntitlementId                 string
	EntitlementDescription        string
	PartnerEarnedCreditPercentage int
	CreditPercentage              int
	CreditType                    string
	BenefitOrderId                string
	BenefitId                     string
	BenefitType                   string
}
